from __future__ import annotations

from dataclasses import dataclass

from booklab.core.contracts import BookDraft, BookRequest, GenerationModel, RetrievalContext


@dataclass(slots=True)
class OpenModelAdapter(GenerationModel):
    model_id: str
    execution_mode: str = "cpu"
    endpoint: str | None = None

    def generate(self, request: BookRequest, context: RetrievalContext | None = None) -> BookDraft:
        rag_note = " with RAG" if context else ""
        chapters = [
            f"# Chapter {idx + 1}\nGenerated by {self.model_id} ({self.execution_mode}){rag_note}."
            for idx in range(request.chapter_count)
        ]
        citations = context.sources if context else []
        return BookDraft(request=request, chapters=chapters, citations=citations)
